<?php

/**
 * Implements hook_init().
 */
function mooc_thumbnav_init() {
  drupal_add_css(drupal_get_path('module', 'mooc_thumbnav') . '/css/mooc_thumbnav.css');
}

/**
 * Implements hook_thumbnav_widget().
 */
function mooc_thumbnav_thumbnav_widget() {
  $widgets = array();
  // detect if we are on a node
  if ($node = menu_get_object()) {
    $widgets = array(
      'mooc_thumbnav_outline' => array(
        'icon' => base_path() . drupal_get_path('module', 'mooc_thumbnav') . '/images/outline.png',
        'title' => t('Course outline'),
        'inc' => drupal_get_path('module', 'mooc_thumbnav') . '/js/mooc_thumbnav_outline.js',
        'weight' => 1,
        'side' => 'right',
      ),
      'mooc_thumbnav_inst_contact' => array(
        'icon' => base_path() . drupal_get_path('module', 'mooc_thumbnav') . '/images/contact_info.png',
        'title' => t('Contact info'),
        'inc' => drupal_get_path('module', 'mooc_thumbnav') . '/js/mooc_thumbnav_inst_contact.js',
        'weight' => 2,
        'side' => 'left',
      ),
      /*'mooc_thumbnav_bookmark' => array(
        'icon' => base_path() . drupal_get_path('module', 'mooc_thumbnav') . '/images/bookmark.png',
        'title' => t('Bookmark page'),
        'inc' => drupal_get_path('module', 'mooc_thumbnav') . '/js/mooc_thumbnav_bookmark.js',
        'weight' => 3,
        'side' => 'right',
      ),
      'mooc_thumbnav_helpdesk' => array(
        'icon' => base_path() . drupal_get_path('module', 'mooc_thumbnav') . '/images/helpdesk.png',
        'title' => t('Contact helpdesk'),
        'inc' => drupal_get_path('module', 'mooc_thumbnav') . '/js/mooc_thumbnav_helpdesk.js',
        'weight' => 4,
        'side' => 'left',
      ),*/
      'mooc_thumbnav_copyright' => array(
        'icon' => base_path() . drupal_get_path('module', 'mooc_thumbnav') . '/images/copyright.png',
        'title' => t('Course copyright info'),
        'inc' => drupal_get_path('module', 'mooc_thumbnav') . '/js/mooc_thumbnav_copyright.js',
        'weight' => 5,
        'side' => 'left',
      ),
    );
  }
  return $widgets;
} 5,
        'side' => 'left',
      ),
    );
  }
  return $widgets;
}