<?php
/**
 * @file
 * Code for the MOOC CIS UX feature.
 */

include_once 'mooc_cis_ux.features.inc';

/**
 * Implements hook_menu().
 */
function mooc_cis_ux_menu() {
  $items = array();
  // Guided tour off of the welcome page with example content
  $items['welcome_page/guided_tour'] = array(
    'title' => 'Guided Tour',
    'page callback' => '_cis_service_connection_page',
    'page arguments' => array(1),
    'menu_name' => 'main-menu',
    'weight' => 10,
    //TODO need to update access argument
    'access arguments' => array('access typo list'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Implements hook_page_build().
 */
function mooc_cis_ux_page_build(&$page) {
  if (user_access('edit any page content')) {
    // make area off to the right side to indicate outline
    $node = menu_get_object();
    if (isset($node->book['bid'])) {
      $query = new EntityFieldQuery();
      // pull all nodes
      $query->entityCondition('entity_type', 'node')
      // that are sections
      ->entityCondition('bundle', 'section')
      // that are published
      ->propertyCondition('status', 1)
      // where field has reference to this book outline
      ->fieldCondition('field_instructional_outlines', 'target_id', $node->book['bid'], '=');
      // store results
      $result = $query->execute();
      // this means this page is in an outline referenced in sections
      // list these by name to help notify people what they are working on
      if (isset($result['node'])) {
        $sections = array();
        $groups = entity_load('node', array_keys($result['node']));
        foreach ($groups as $group) {
          $sections[$group->nid] = $group->field_section_id['und'][0]['safe_value'];
          // useful for custom college / university integrations
          drupal_alter('cis_section_list', $sections);
        }
        // see if we should print anything
        if (!empty($sections)) {
          // list sections out
          $output = '<div id="mooc_active_outline_flag">';
          foreach($sections as $key => $section) {
            $output .= l($section, 'node/' . $key) . ' ';
          }
          $output .= '</ul></div>';
          // append output to screen to indicate section relation
          drupal_add_css(drupal_get_path('module', 'mooc_cis_ux') . '/mooc_cis_ux.css');
          $page['page_bottom']['mooc_cis_ux'] = array(
            '#weight' => 100,
            '#type' => 'markup',
            '#markup' => $output,
          );
        }
      }
    }
  }
}