<?php

/**
 * Implements hook_page_build().
 */
function mooc_helper_page_build($page) {
  // add css related to mooc helper instance
  drupal_add_css(drupal_get_path('module', 'mooc_helper') . '/css/mooc_helper.css');
}

/**
 * Implements hook_menu().
 */
function mooc_helper_menu() {
  $items = array();
  // Callback to load correct instructional outline
  $items['inst-outline'] = array(
    'title' => 'Instructional outline',
    'page callback' => '_cis_connector_transaction',
    'page arguments' => array(0),
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );
  // fix for typo shortcut
  $items['typo-shortcut'] = array(
    'title' => 'Typo',
    'page callback' => 'drupal_goto',
    'page arguments' => array('typo-reports'),
    'type' => MENU_CALLBACK,
    'access arguments' => array('access typo list'),
  );
  return $items;
}

/**
 * Return a list of all book roots as an array
 */
function _mooc_helper_all_book_outlines($property = 'uuid', $title = '') {
  $outlines = array();
  // load all book outline etids
  foreach (book_get_books() as $book_id => $book) {
    // load book node fully
    $node = node_load($book['nid']);
    if ($title == '') {
      $set_title = $node->book['link_title'];
    }
    else {
      $set_title = $node->{$title};
    }
    // create an array
    $outlines[$node->{$property}] = $set_title;
  }
  return $outlines;
}

/**
 * Implements hook_node_insert().
 */
function mooc_helper_node_insert(&$node) {
  // insert evaluation needs to process same as update
  mooc_helper_node_update($node);
}

/**
 * Implements hook_node_update().
 */
function mooc_helper_node_update(&$node) {
  // make sure there's an outline associated to this
  // but only if we have at least 1 to do so with
  if ($node->type == 'section') {
    // ensure an outline is set, if not use default
    if (!isset($node->field_instructional_outlines['und'])) {
      $default = variable_get('mooc_default_outline', '');
      // edge case, default was never set
      if ($default == '') {
        // load all books
        $books = _mooc_helper_all_book_outlines('nid', 'created');
        // make sure we at least have some books in here
        if (is_array($books)) {
          // move to 1st array position in iterator
          reset($books);
          // sort maintaining index which is the nid
          asort($books);
          // set default to first key in array
          $default = key($books);
        }
      }
      // make sure we have something to set
      if ($default != '') {
        $node->field_instructional_outlines['und'][0]['value'] = $default; 
      }
    }
  }
}

/**
 * Page callback for cis_service_connection_ux.
 */
function mooc_helper_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'cis_service_connection_ux_form') {
    $form['site_information']['mooc_default_outline'] = array(
      '#description' => t('This is the default content outline for new sections that register.'),
      '#default_value' => variable_get('mooc_default_outline', ''),
      '#weight' => '0',
      '#title' => t('Default Outline'),
      '#type' => 'select',
      '#required' => '1',
      '#options' => _mooc_helper_all_book_outlines('nid'),
    );
  }
}

/**
 * Implementation of hook_feeds_after_import().
 */
function mooc_helper_feeds_after_import(FeedsSource $source) {
  //TODO: Convert to D7 code
  // need to clear the UUIDs of all imported nodes from the
  // get a list of nodes that were just imported
  //$ary = array();
  /*$result = db_query("SELECT nid FROM {feeds_node_item} WHERE id='elms_node_import'");
  while ($val = db_fetch_array($result)) {
    $ary[] = $val['nid'];
  }
  if (count($ary) != 0) {
    // clear all nodes that came across
    db_query("DELETE FROM {uuid_node} WHERE nid IN(". db_placeholders($ary) .")", $ary);
    // clean up revisions if they exist
    db_query("DELETE FROM {uuid_node_revisions} WHERE nid IN(". db_placeholders($ary) .")", $ary);
    // clean up original import table
    db_query("DELETE FROM {feeds_node_item} WHERE id='elms_node_import'");
    // seed all nodes by saving them all again
    foreach ($ary as $nid) {
      $node = node_load($nid);
      $node->uuid = uuid_uuid();
      $node->revision_uuid = uuid_uuid();
      node_save($node);
    }
  }*/
}